workspace:
  path: /

pipeline:

  deploy:
    image: cschlosser/drone-ftps
    hostname: web.linux.pizza:21
    secrets: [ ftp_username, ftp_password ]
    username:
      from_secret: ftp_username
    password:
      from_secret: ftp_password
    clean_dir: true
    chmod: false
    secure: true
    verify: false
    dest_dir: public/
    src_dir: /htdocs/

  notify:
    image: plugins/matrix
    settings:
    homeserver: https://matrix.selea.se
    roomid: YQaSpONowlLzEbWZNt:matrix.selea.se
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
