workspace:
  path: /

pipeline:
  master:
    when:
       branch: master
    ssh:
    image: appleboy/drone-ssh
    host: web.linux.pizza
    username: root
    port: 22
    secrets: [ ssh_key ]
    script:
       - cd /home/web
       - rm master.zip*
       - wget https://git.selea.se/jonathan/lp-landingpage/archive/master.zip
       - rm -rf lp-landingpage
       - unzip master.zip
       - rm master.zip
       - rm drone.yml
       - chown -R web:web /home/web
       - echo "done"

  dev:
    when:
       branch: dev
    ssh:
    image: appleboy/drone-ssh
    host: web.linux.pizza
    username: root
    port: 22
    secrets: [ ssh_key ]
    script:
       - cd /home/dev
       - rm dev.zip*
       - wget https://git.selea.se/jonathan/lp-landingpage/archive/dev.zip
       - rm -rf lp-landingpage
       - unzip dev.zip
       - rm dev.zip
       - rm drone.yml
       - chown -R dev:dev /home/dev
       - echo "done"

  notify:
    when:
    when:
      status: [ success, failure, change ]
    image: plugins/matrix
    settings:
    homeserver: https://matrix.org
    roomid: jNNkLoxzHAkxIUJqKl:matrix.org
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
