workspace:
  path: /

pipeline:
  deploy:
    ssh:
    image: appleboy/drone-ssh
    host: web.linux.pizza
    username: root
    port: 22
    secrets: [ ssh_key ]
    script:
       - cd /home/web/
       - wget https://git.selea.se/jonathan/lp-landingpage/archive/master.zip
       - unzip master.zip
       - echo "done"

  notify:
    when:
      success: false
      failure: true
      change: true
    image: plugins/matrix
    settings:
    homeserver: https://matrix.selea.se
    roomid: YQaSpONowlLzEbWZNt:matrix.selea.se
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
