pipeline:
  build:
    image: debian:latest
    commands: 
        - sed -i -e s/deb.debian.org/mirror.linux.pizza/g /etc/apt/sources.list
        - apt-get update
        - apt-get upgrade -y
        - apt-get install apache2 -y
  test:
    image: debian:latest
    commands:
        - apache2 --version
  notify:
    image: drillster/drone-email
    from: drone@selea.tech
    recipients: [ jonathan@selea.se ]
    secrets: [ 192.168.25.25, 25 ]
